import './apropos.css'
import React from 'react';

const Apropos = () => {
    return (
        <div>
            <h1>A propos</h1>
            <p className='aproposText'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sit amet libero ac eros pulvinar sodales. Nulla facilisi. Cras id arcu risus. Mauris ultricies, ligula vel luctus sagittis, enim urna convallis nulla, id interdum justo velit sed tortor. Nunc non ante non nulla lobortis dapibus. Duis vitae nisi vel tellus volutpat iaculis. Nam sit amet hendrerit mauris, nec convallis est. Etiam consequat vestibulum lobortis. Donec auctor aliquet tellus, in rhoncus leo sollicitudin in. Sed convallis fermentum dolor, ut lacinia nulla auctor in. Donec nec velit auctor, sollicitudin augue id, pretium ligula.
Praesent consequat lorem a libero tempus, quis scelerisque nunc commodo. Nulla facilisi. Nulla facilisi. Integer ac nisi ut nunc maximus ultrices. Nullam fermentum sapien id purus lobortis, nec congue risus eleifend. Nullam nec ullamcorper eros. Aliquam a velit auctor, ultricies nulla a, faucibus lorem. Duis eget scelerisque ex. Cras sed sollicitudin justo, in consectetur nisi. Ut tempus tincidunt libero, eget sollicitudin neque. Mauris semper nunc in dui dictum, a convallis neque aliquet. Proin aliquet purus vel felis bibendum, id dignissim purus consequat.
Suspendisse potenti. Maecenas eu convallis ligula. Morbi at diam ut ligula iaculis tincidunt vel id arcu. Nam nec commodo urna. Nam id purus vel nulla fermentum faucibus. Nulla facilisi. Morbi consequat a magna vitae vehicula. Quisque lacinia, libero eget aliquet laoreet, nunc nisi consequat mi, eu tempus felis felis non elit. Aliquam ut ultricies lacus. Curabitur vel erat nec eros tempor fringilla. Vivamus eleifend ligula at sem fermentum, sed vestibulum dolor malesuada.
Phasellus fermentum libero a magna eleifend interdum. Proin rutrum ipsum id augue dictum, a ultricies nulla pellentesque. In a lacinia metus, nec volutpat felis. Mauris eget est ut libero venenatis malesuada non ac odio. Etiam at ante ultricies, rutrum ipsum sed, fermentum lectus. Nam eget enim consequat, ultricies metus id, consectetur libero. Fusce eget dui felis. Ut efficitur, arcu quis convallis sagittis, nisi risus congue nunc, sit amet venenatis metus ipsum non lorem.
Sed auctor est ac enim laoreet, vitae consequat nunc pellentesque. Quisque nec quam odio. Aenean semper a dui in hendrerit. Nulla facilisi. Suspendisse non ligula tellus. Curabitur a diam condimentum, laoreet lorem et, bibendum nisi. Etiam id arcu fermentum, pharetra nulla in, malesuada tellus. Nam ultrices velit in odio luctus, et hendrerit elit ultricies. Integer scelerisque quam a massa suscipit, at consequat lectus congue. Nullam id felis ac orci venenatis tincidunt. Nullam suscipit ipsum sit amet semper blandit.
Sed vulputate risus eget lorem ultricies, ac maximus lorem convallis. Cras convallis eros nec efficitur pellentesque. Nullam aliquet lacinia augue, in tristique felis venenatis eget. In consectetur urna vel sem tempus, sit amet iaculis libero feugiat. Ut sed tempor nunc. Fusce tincidunt scelerisque lacus, non tempus nisl dictum et. Vivamus tincidunt auctor sodales. Vestibulum a odio a enim ullamcorper egestas. Duis auctor sem nec eros consequat, vel eleifend eros consectetur. Proin et mauris id velit tempor venenatis in ac ligula.
</p>
<p className='aproposText'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sit amet libero ac eros pulvinar sodales. Nulla facilisi. Cras id arcu risus. Mauris ultricies, ligula vel luctus sagittis, enim urna convallis nulla, id interdum justo velit sed tortor. Nunc non ante non nulla lobortis dapibus. Duis vitae nisi vel tellus volutpat iaculis. Nam sit amet hendrerit mauris, nec convallis est. Etiam consequat vestibulum lobortis. Donec auctor aliquet tellus, in rhoncus leo sollicitudin in. Sed convallis fermentum dolor, ut lacinia nulla auctor in. Donec nec velit auctor, sollicitudin augue id, pretium ligula.
Praesent consequat lorem a libero tempus, quis scelerisque nunc commodo. Nulla facilisi. Nulla facilisi. Integer ac nisi ut nunc maximus ultrices. Nullam fermentum sapien id purus lobortis, nec congue risus eleifend. Nullam nec ullamcorper eros. Aliquam a velit auctor, ultricies nulla a, faucibus lorem. Duis eget scelerisque ex. Cras sed sollicitudin justo, in consectetur nisi. Ut tempus tincidunt libero, eget sollicitudin neque. Mauris semper nunc in dui dictum, a convallis neque aliquet. Proin aliquet purus vel felis bibendum, id dignissim purus consequat.
Suspendisse potenti. Maecenas eu convallis ligula. Morbi at diam ut ligula iaculis tincidunt vel id arcu. Nam nec commodo urna. Nam id purus vel nulla fermentum faucibus. Nulla facilisi. Morbi consequat a magna vitae vehicula. Quisque lacinia, libero eget aliquet laoreet, nunc nisi consequat mi, eu tempus felis felis non elit. Aliquam ut ultricies lacus. Curabitur vel erat nec eros tempor fringilla. Vivamus eleifend ligula at sem fermentum, sed vestibulum dolor malesuada.
Phasellus fermentum libero a magna eleifend interdum. Proin rutrum ipsum id augue dictum, a ultricies nulla pellentesque. In a lacinia metus, nec volutpat felis. Mauris eget est ut libero venenatis malesuada non ac odio. Etiam at ante ultricies, rutrum ipsum sed, fermentum lectus. Nam eget enim consequat, ultricies metus id, consectetur libero. Fusce eget dui felis. Ut efficitur, arcu quis convallis sagittis, nisi risus congue nunc, sit amet venenatis metus ipsum non lorem.
Sed auctor est ac enim laoreet, vitae consequat nunc pellentesque. Quisque nec quam odio. Aenean semper a dui in hendrerit. Nulla facilisi. Suspendisse non ligula tellus. Curabitur a diam condimentum, laoreet lorem et, bibendum nisi. Etiam id arcu fermentum, pharetra nulla in, malesuada tellus. Nam ultrices velit in odio luctus, et hendrerit elit ultricies. Integer scelerisque quam a massa suscipit, at consequat lectus congue. Nullam id felis ac orci venenatis tincidunt. Nullam suscipit ipsum sit amet semper blandit.
Sed vulputate risus eget lorem ultricies, ac maximus lorem convallis. Cras convallis eros nec efficitur pellentesque. Nullam aliquet lacinia augue, in tristique felis venenatis eget. In consectetur urna vel sem tempus, sit amet iaculis libero feugiat. Ut sed tempor nunc. Fusce tincidunt scelerisque lacus, non tempus nisl dictum et. Vivamus tincidunt auctor sodales. Vestibulum a odio a enim ullamcorper egestas. Duis auctor sem nec eros consequat, vel eleifend eros consectetur. Proin et mauris id velit tempor venenatis in ac ligula.
</p>


        </div>
    );
};

export default Apropos;
